- name: Install and secure packages
  hosts: target
  become: yes
  roles:
    - ssh-secured
    - lets-encrypt-use-certificate
    - rootkit-checks-enabled
    - logwatch-enabled
    - forward-root-mails
