- name: Install Ansible Python Tools
  package:
    name:
      - python3-pip
      - python3-pymysql
    state: present
- name: Install Python Packages
  pip:
    name: "{{ item }}"
  loop:
    - pip
    - pexpect
    - docker