- name: Install Dovecot
  package:
    name:
      - dovecot-imapd
      - dovecot-pop3d
      - dovecot-mysql
      - dovecot-sieve
      - dovecot-lmtpd
      # - dovecot-managesieved
    state: present
