- name: Get lsb name of host
  command: "lsb_release -c -s"
  register: host_lsb_name
- name: Add an Apt signing key for packages.sury.org
  apt_key:
    url: https://packages.sury.org/php/apt.gpg
    state: present
- name: Add apt-sources to php of sury.org
  template:
    src: php.list
    dest: /etc/apt/sources.list.d/php.list
    mode: "0644"
- name: "Update apt cache"
  apt:
    update_cache: yes
- name: Install PHP 7.2
  vars:
    php_version: "7.2"
  package:
    name:
      - php{{ php_version }}
      - php{{ php_version }}-cli
      - php{{ php_version }}-cgi
      - php{{ php_version }}-fpm
      - php{{ php_version }}-gd
      - php{{ php_version }}-mysql
      - php{{ php_version }}-imap
      - php{{ php_version }}-curl
      # - php{{ php_version }}-intl
      # - php{{ php_version }}-pspell
      # - php{{ php_version }}-recode
      # - php{{ php_version }}-sqlite3
      # - php{{ php_version }}-tidy
      # - php{{ php_version }}-xmlrpc
      # - php{{ php_version }}-xsl
      - php{{ php_version }}-zip
      - php{{ php_version }}-mbstring
      # - php{{ php_version }}-soap
      # - php{{ php_version }}-opcache
      # - php{{ php_version }}-common
      - php{{ php_version }}-json
      # - php{{ php_version }}-readline
      - php{{ php_version }}-xml
      - php{{ php_version }}-memcache
      - php{{ php_version }}-memcached
      - libapache2-mod-php{{ php_version }}
    state: present
- name: Install PHP 7.3
  vars:
    php_version: "7.3"
  package:
    name:
      - php{{ php_version }}
      - php{{ php_version }}-cli
      - php{{ php_version }}-cgi
      - php{{ php_version }}-fpm
      - php{{ php_version }}-gd
      - php{{ php_version }}-mysql
      - php{{ php_version }}-imap
      - php{{ php_version }}-curl
      # - php{{ php_version }}-intl
      # - php{{ php_version }}-pspell
      # - php{{ php_version }}-recode
      # - php{{ php_version }}-sqlite3
      # - php{{ php_version }}-tidy
      # - php{{ php_version }}-xmlrpc
      # - php{{ php_version }}-xsl
      - php{{ php_version }}-zip
      - php{{ php_version }}-mbstring
      # - php{{ php_version }}-soap
      # - php{{ php_version }}-opcache
      # - php{{ php_version }}-common
      - php{{ php_version }}-json
      # - php{{ php_version }}-readline
      - php{{ php_version }}-xml
      - php{{ php_version }}-memcache
      - php{{ php_version }}-memcached
      - libapache2-mod-php{{ php_version }}
    state: present
- name: Install PHP 7.4
  vars:
    php_version: "7.4"
  package:
    name:
      - php{{ php_version }}
      - php{{ php_version }}-cli
      - php{{ php_version }}-cgi
      - php{{ php_version }}-fpm
      - php{{ php_version }}-gd
      - php{{ php_version }}-mysql
      - php{{ php_version }}-imap
      - php{{ php_version }}-curl
      # - php{{ php_version }}-intl
      # - php{{ php_version }}-pspell
      # - php{{ php_version }}-sqlite3
      # - php{{ php_version }}-tidy
      # - php{{ php_version }}-xmlrpc
      # - php{{ php_version }}-xsl
      - php{{ php_version }}-zip
      - php{{ php_version }}-mbstring
      # - php{{ php_version }}-soap
      # - php{{ php_version }}-opcache
      # -libonig5
      # - php{{ php_version }}-common
      - php{{ php_version }}-json
      # - php{{ php_version }}-readline
      - php{{ php_version }}-xml
      - php{{ php_version }}-memcache
      - php{{ php_version }}-memcached
      - libapache2-mod-php{{ php_version }}
    state: present
- name: Set standard php version
  alternatives:
    name: php
    path: /usr/bin/php7.3
- name: Set standard php-cgi version
  alternatives:
    name: php-cgi
    path: /usr/bin/php-cgi7.3
- name: Restart FPM daemons of installed php versions
  service:
    name: "{{ item }}"
    state: restarted
  loop:
    - php7.2-fpm
    - php7.3-fpm
    - php7.4-fpm   